function h = plot_camera_fov(ax, cam_pos, cam_roll, cam_pitch, cam_yaw, ...
    fov_x, fov_y, fov_range_max, color)
% Plot the camera's FOV
%
% Input:
%   ax: axis handle for plotting
%   cam_pos: camera position, [3x1], m
%   cam_roll: camera roll, rad
%   cam_pitch: camera pitch, rad
%   cam_yaw: camera yaw, rad
%   fov_x: FOV horizontal angle
%   fov_y: FOV vertical angle
%   fov_range_max: FOV depth range max
%   color: plotting color
% ---
% Output:
%   h: handle of the camera FOV


    % compute the four "bottom" points under zero pitch and yaw
    % and as camera at origin
    bottom_dy = fov_range_max * tan(0.5*fov_x);
    bottom_dz = fov_range_max * tan(0.5*fov_y);
    upper_left = [fov_range_max; bottom_dy; bottom_dz];
    upper_right = [fov_range_max; -bottom_dy; bottom_dz];
    lower_left = [fov_range_max; bottom_dy; -bottom_dz];
    lower_right = [fov_range_max; -bottom_dy; -bottom_dz];
    
    % rotation and translation
    R = rotz(rad2deg(cam_yaw))*rotx(rad2deg(cam_roll))*roty(rad2deg(cam_pitch));
    upper_left = R*upper_left + cam_pos;
    upper_right = R*upper_right + cam_pos;
    lower_left = R*lower_left + cam_pos;
    lower_right = R*lower_right + cam_pos;
    
    % plot camera at the position
    h_pos = plot3(ax, cam_pos(1), cam_pos(2), cam_pos(3), ...
        'Color', color, 'Marker', 'x', 'MarkerSize', 10);
    
    % plot side lines
%     h_side_line_1 = plot3(ax, [cam_pos(1), upper_left(1)], ...
%         [cam_pos(2), upper_left(2)], [cam_pos(3), upper_left(3)], ...
%         'Color', color, 'LineStyle', '-', 'LineWidth', 1.5);
%     h_side_line_2 = plot3(ax, [cam_pos(1), upper_right(1)], ...
%         [cam_pos(2), upper_right(2)], [cam_pos(3), upper_right(3)], ...
%         'Color', color, 'LineStyle', '-', 'LineWidth', 1.5);
%     h_side_line_3 = plot3(ax, [cam_pos(1), lower_left(1)], ...
%         [cam_pos(2), lower_left(2)], [cam_pos(3), lower_left(3)], ...
%         'Color', color, 'LineStyle', '-', 'LineWidth', 1.5);
%     h_side_line_4 = plot3(ax, [cam_pos(1), lower_right(1)], ...
%         [cam_pos(2), lower_right(2)], [cam_pos(3), lower_right(3)], ...
%         'Color', color, 'LineStyle', '-', 'LineWidth', 1.5);
    
    % plot bottom lines
%     h_bottom_line_1 = plot3(ax, [upper_right(1), upper_left(1)], ...
%         [upper_right(2), upper_left(2)], [upper_right(3), upper_left(3)], ...
%         'Color', color, 'LineStyle', '-', 'LineWidth', 1.5);
%     h_bottom_line_2 = plot3(ax, [lower_right(1), upper_right(1)], ...
%         [lower_right(2), upper_right(2)], [lower_right(3), upper_right(3)], ...
%         'Color', color, 'LineStyle', '-', 'LineWidth', 1.5);
%     h_bottom_line_3 = plot3(ax, [lower_right(1), lower_left(1)], ...
%         [lower_right(2), lower_left(2)], [lower_right(3), lower_left(3)], ...
%         'Color', color, 'LineStyle', '-', 'LineWidth', 1.5);
%     h_bottom_line_4 = plot3(ax, [upper_right(1), lower_right(1)], ...
%         [upper_right(2), lower_right(2)], [upper_right(3), lower_right(3)], ...
%         'Color', color, 'LineStyle', '-', 'LineWidth', 1.5);
    
    % plot side patches
    h_side_patch_1 = patch(ax, [cam_pos(1), lower_left(1), upper_left(1)], ...
        [cam_pos(2), lower_left(2), upper_left(2)], ...
        [cam_pos(3), lower_left(3), upper_left(3)], ...
        color, 'FaceColor', color, 'FaceAlpha', 0.1, ...
        'EdgeColor', color);
    h_side_patch_2 = patch(ax, [cam_pos(1), upper_right(1), upper_left(1)], ...
        [cam_pos(2), upper_right(2), upper_left(2)], ...
        [cam_pos(3), upper_right(3), upper_left(3)], ...
        color, 'FaceColor', color, 'FaceAlpha', 0.1, ...
        'EdgeColor', color);
    h_side_patch_3 = patch(ax, [cam_pos(1), upper_right(1), lower_right(1)], ...
        [cam_pos(2), upper_right(2), lower_right(2)], ...
        [cam_pos(3), upper_right(3), lower_right(3)], ...
        color, 'FaceColor', color, 'FaceAlpha', 0.1, ...
        'EdgeColor', color);
    h_side_patch_4 = patch(ax, [cam_pos(1), lower_left(1), lower_right(1)], ...
        [cam_pos(2), lower_left(2), lower_right(2)], ...
        [cam_pos(3), lower_left(3), lower_right(3)], ...
        color, 'FaceColor', color, 'FaceAlpha', 0.1, ...
        'EdgeColor', color);
    
    % plot bottom patch
    h_bottom_patch = patch(ax, ...
        [upper_left(1), upper_right(1), lower_right(1), lower_left(1)], ...
        [upper_left(2), upper_right(2), lower_right(2), lower_left(2)], ...
        [upper_left(3), upper_right(3), lower_right(3), lower_left(3)], ...
        color, 'FaceColor', color, 'FaceAlpha', 0.1, ...
        'EdgeColor', color);
    
    % return plot handles
    h = [h_pos; h_side_patch_1; h_side_patch_2; h_side_patch_3; h_side_patch_4; ...
        h_bottom_patch];

end

%% examples
% hfig = figure;
% hold on;
% axis equal;
% ax = hfig.CurrentAxes;
% xlabel('x [m]');
% ylabel('y [m]');
% zlabel('z [m]');
% cam_pos = [2;1;3];
% cam_roll = deg2rad(0);
% cam_pitch = deg2rad(15);
% cam_yaw = deg2rad(60);
% fov_x = deg2rad(120);
% fov_y = deg2rad(90);
% fov_range_max = 5;
% color = 'r';
% h = plot_camera_fov(ax, cam_pos, cam_roll, cam_pitch, cam_yaw, ...
%     fov_x, fov_y, fov_range_max, color);